project_id = "pvsuqbmcivemnfedmncm"

[functions.generate-parent-child-dynamics]
verify_jwt = false

[functions.generate-sibling-dynamics]
verify_jwt = false

[functions.generate-relationship-insights]
verify_jwt = false

[functions.generate-partner-insights]
verify_jwt = false
